version: "3.9"

services:

  test_db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "test_postgres"
      POSTGRES_USER: "test_postgres"
      POSTGRES_PASSWORD: "test_postgres"
    ports:
      - "9999:5432"

  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres2"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      DB_HOST: "localhost"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data

  backend:
    depends_on:
      - db
    build: './backend'
    ports:
      - 80:8000
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres2
      - TEST_DB_URL=postgresql+asyncpg://test_postgres:test_postgres@test_db:9999/test_postgres
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRE_MIN=1_000_000
      - JWT_SECRET=SomeJwtSecret