"""Firsst2

Revision ID: 06c51267c277
Revises: cf17c19c011d
Create Date: 2023-04-26 16:48:03.697818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c51267c277'
down_revision = 'cf17c19c011d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.Text(), nullable=False, comment='Хэш пароля'))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=False, comment='Хэш пароля'))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
