"""empty message

Revision ID: 09163d048cc9
Revises: f56524a83f74
Create Date: 2023-05-01 20:33:05.027618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09163d048cc9'
down_revision = 'f56524a83f74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'photos', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='unique')
    # ### end Alembic commands ###
