"""user role

Revision ID: 41aeaf04d1c5
Revises: 06c51267c277
Create Date: 2023-04-27 11:13:28.453614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aeaf04d1c5'
down_revision = '06c51267c277'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
