"""user role

Revision ID: 41d9b1043ee9
Revises: 41aeaf04d1c5
Create Date: 2023-04-27 12:00:27.072474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d9b1043ee9'
down_revision = '41aeaf04d1c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время регистрации пользователя.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registred_at')
    # ### end Alembic commands ###
