"""empty message

Revision ID: 6974109ddd01
Revises: 8826975725e2
Create Date: 2023-05-02 16:42:47.414640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6974109ddd01'
down_revision = '8826975725e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Идентификатор в БД'),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Владелец фотограции. (User)'),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='Текстовое описание фотографии.'),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('image_uri', sa.TEXT(), autoincrement=False, nullable=False, comment='Ссылка на доступ к фотографии.'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='photos_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photos_pkey')
    )
    # ### end Alembic commands ###
