"""photos

Revision ID: 76fc00120bf9
Revises: 962c53deff1a
Create Date: 2023-04-27 23:31:36.001482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76fc00120bf9'
down_revision = '962c53deff1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор в БД'),
    sa.Column('data', sa.LargeBinary(), nullable=False, comment='Байтовое представление фотографии'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='Владелец фотограции. (User)'),
    sa.Column('description', sa.String(length=300), nullable=True, comment='Текстовое описание фотографии.'),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
