"""empty message

Revision ID: 8826975725e2
Revises: ffe2b9ac24ab
Create Date: 2023-05-01 23:43:32.223878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8826975725e2'
down_revision = 'ffe2b9ac24ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photos_owner_id_key', 'photos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('photos_owner_id_key', 'photos', ['owner_id'])
    # ### end Alembic commands ###
