"""empty message

Revision ID: 962c53deff1a
Revises: eede5d19550d
Create Date: 2023-04-27 22:59:03.464409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '962c53deff1a'
down_revision = 'eede5d19550d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Идентификатор в БД'),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False, comment='Байтовое представление фотографии'),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Владелец фотограции. (User)'),
    sa.Column('description', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='Текстовое описание фотографии.'),
    sa.Column('added_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='photos_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photos_pkey')
    )
    # ### end Alembic commands ###
