"""photos relations

Revision ID: c200390a0704
Revises: 0ec3b1087dcb
Create Date: 2023-04-27 13:24:03.111977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c200390a0704'
down_revision = '0ec3b1087dcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
