"""Firsst

Revision ID: cf17c19c011d
Revises: 
Create Date: 2023-04-26 15:44:03.048375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf17c19c011d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Id пользователя'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Псеводним'),
    sa.Column('hashed_password', sa.Text(), nullable=False, comment='Хэш пароля'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Флаг активен ли пользователь.'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
