"""empty message

Revision ID: ffe2b9ac24ab
Revises: f20551a7a338
Create Date: 2023-05-01 21:08:09.639043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe2b9ac24ab'
down_revision = 'f20551a7a338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'photos', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='unique')
    # ### end Alembic commands ###
